# https://github.com/thesimj/envyaml
# Use $ENV_NAME to retrieve environment variable

# Set both values to None if not using a domain name.
route53:
  zone_name: christiandeleon.me
  domain_name: christiandeleon.me # Match zone_name if not using a subdomain e.g. christiandeleon.me

account:
  id: "$PORTFOLIO_ACCT_ID" # Retrieve from environment variable or replace with your account id in string format

github:
  owner: christian-deleon # GitHub account name
  repo: portfolio # GitHub repository name
